### PR TITLE
add g5_ops gem, bump version to 1.0.0

### PR DESCRIPTION
**Pull request by thescubageek**
* Adds the g5_ops gem
* Bumps version to 1.0.0

### CODE REVIEW

**Comment by johnmendonca** [comment]
:+1:

**Comment by variousred** [comment]
@thescubageek dont want to add the token to the fury url there

**Comment by thescubageek** [comment]
@variousred Updated without gemfury token

**Comment by thescubageek** [comment]
@variousred What needs to be done to get the specs to pass without the gemfury token in the Gemfile?

**Pull request merged**
